# fly.toml app configuration file generated for full-stack-open-pokedex-quiet-tree-3285 on 2025-05-03T09:21:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-quiet-tree-3285'
primary_region = 'arn'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  strategy = "canary"

[[http_service.checks]]
  grace_period = "5s"
  interval = "30s"
  timeout = "5s"
  method = "GET"
  path = "/health"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
